development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: blog
  pool: 5
  username: postgres
  password: Chescomanboy1

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: blog_test
  pool: 5
  username: postgres
  password: Chescomanboy1